version: "2"
services: 
  rocm-a1111:
    cap_add:
      - SYS_PTRACE
    # devices:
    #   - /dev/kfd:/dev/kfd
    #   - /dev/dri:/dev/dri
    ipc: host
    security_opt:
      - seccomp:unconfined
    # group_add:
    #   - video
    #   - render
    ports:
      - 7860:7860
    volumes:
      - ./app:/root/app
    build: .

    # Runtime variables
    environment:
      # PyTorch index override for ROCm
      - PYTORCH_INDEX=https://download.pytorch.org/whl/rocm5.7
      # Needed for 6XXX series GPUs
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      # Allows for more use of the VRAM cache
      - PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:256
      # Web-UI repository
      - WEBUI_REPO=https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
      # Force update Web-UI repository
      - WEBUI_UPDATE=
      # Web-UI launch parameters
      - WEBUI_PARAMS=--use-cpu all --no-half --skip-torch-cuda-test --enable-insecure-extension-access --no-download-sd-model --do-not-download-clip
