version: "2"
services: 
  singleton:
    container_name: rocm-a1111
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    ipc: host
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
      - render
    ports:
      - 7860:7860
    volumes:
      - ./app:/root/app
    build: .

    # Runtime variables
    environment:
      # https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings
      - COMMANDLINE_ARGS=--listen --enable-insecure-extension-access --no-download-sd-model
      # PyTorch index override for ROCm
      - TORCH_INDEX=https://download.pytorch.org/whl/rocm5.7
      # Web-UI repository
      - REPO=https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
      # Force update Web-UI repository, empty for false
      - UPDATE=
      # Web-UI arguments
      # Needed for 6XXX series GPUs
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      # Allows for more use of the VRAM cache
      - PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:256
