version: "2"
services: 
  rocm-a1111:
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    ipc: host
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
      - render
    ports:
      - 7860:7860
    volumes:
      - ./app:/root/app

    # Build-time variables
    build:
      context: .
      args:
        # Web-UI repository
        - A1111_REPO=https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
        # PyTorch index override for ROCm
        - PYTORCH_INDEX=https://download.pytorch.org/whl/rocm5.6

    # Runtime variables
    environment: 
      # Needed for 6XXX series GPUs
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      # Allows for more use of the VRAM cache
      - PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:256
      
    # Web-UI parameters
    command: --precision full --no-half --no-download-sd-model